module.exports = {
  Character: require("./character"),
  Series: require("./series"),
  Notes: require("./notes"),
  Userbooks: require("./userbooks"),
  Userhighscoretrivia: require("./userhighscoretrivia"),
  Userhighscorememory: require("./userhighscorememory"),
  userprofilecustom: require("./userprofilecustom"),
 userbookstoloan: require("./userbookstolend"),
 userbooksloaned: require("./userbooksloaned"),
  userblog: require("./userblog"),
  userfavblogs: require("./userfavblogs"),
  comicvinevolumes: require("./comicvinevolumes"),
  products: require("./products"),
  productsbought: require("./productsbought"),
  wishlist: require("./wishlist"),
  mycart: require("./mycart"),
  userfavtv: require("./userfavtv"),
  favcharacters: require("./favcharacters")
  // userfavmovies: require("./"),
  // userfavnews: require("./"),
};
